[workspace]
resolver = "3"
members = ["waka", "waka-cli"]

[workspace.package]
authors = ["Markus Mayer"]
version = "0.2.1"
edition = "2024"
rust-version = "1.87"
license = "EUPL-1.2"
repository = "https://github.com/sunsided/waka-rs"

[workspace.dependencies]
# Workspace crates
waka = { version = "0.2.1", path = "waka" }

# Dependencies
base64 = "0.22"
clap = { version = "4.5", features = ["derive", "env"] }
clap_complete = "4.5"
dotenvy = "0.15.7"
percent-encoding = "2"
query-string-builder = "0.7"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
tokio = "1.52.3"

# Dev dependencies
assert2 = "0.4"
wiremock = "0.6"
